### ISSUE TITLE
New version > CRAN take two

### ISSUE THREAD

**Issue by jooolia** [ropensci/rsnps#102]
We were working towards a new version on CRAN in #71 but were waylaid by many of the NCBI functions that were no longer properly working. We will close #71 and prepare for a new release in this issue. So completeness I have kept the same list as in #71 even though I think several of the items are already complete. 

From https://github.com/r-lib/usethis/issues/338

Prepare for release:

* [x] `devtools::check_win_devel()`
1 Note: Maintainer: 'Julia Gustavsen <j.gustavsen@gmail.com>' seems to be ok based on 
https://mailman.stat.ethz.ch/pipermail/r-devel/2014-March/068497.html
* [x] `rhub::check_for_cran()`:
Linux distros have the same note as above for the maintainer:
rsnps 0.3.2.9121: NOTE Platform: | Ubuntu Linux 16.04 LTS, R-release, GCC
https://builder.r-hub.io/status/rsnps_0.3.2.9121.tar.gz-e8127d069c0b4abc9657e2a1951bc3a6
rsnps 0.3.2.9121: NOTE Platform: | Fedora Linux, R-devel, clang, gfortran
https://builder.r-hub.io/status/rsnps_0.3.2.9121.tar.gz-4a669680d60c47ebb1c44d5885de7649
**Windows has this error:**
rsnps 0.3.2.9121: ERROR Platform: | Windows Server 2008 R2 SP1, R-devel, 32/64 bit 
checking package dependencies ... ERROR
Package required but not available: 'data.table'
https://builder.r-hub.io/status/rsnps_0.3.2.9121.tar.gz-a439a712d233486da4b75e700a6bb44d
Lines 255-257:
> #> Package which is only available in source form, and may need
> #> These will not be installed
> #> compilation of C/C++/Fortran: 'data.table'

* Trying again with 
`rhub::check_for_cran(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")` as {data.table} was not compiled and thus not installed.
This command gave: 
rsnps 0.3.2.9121: NOTE (as above about maintainer) Platform: | Windows Server 2008 R2 SP1, R-devel, 32/64 bit
https://builder.r-hub.io/status/rsnps_0.3.2.9121.tar.gz-a3cf0e4f3a314cdda42a83b1c48edb8b

* [x] `revdepcheck::revdep_check(num_workers = 4, timeout = as.difftime(360,units = "mins"))`

    * revdepcheck no longer on CRAN? (opened issue https://github.com/r-lib/revdepcheck/issues/263), installed with:
`devtools::install_github("r-lib/revdepcheck")`
   * opened PR #107 to merge in updates to revdep folder readme to document this check. 

* [x] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()` -no new failures
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
   * opened PR #111 for this.
* [x] update comments-cran.md
   * opened PR #112 for this.
* [x] update codemeta.json using `codemetar::write_codemeta(".")` (from within project folder on dev branch)
   * opened PR #108 for this.
* [x] update LICENSE to reflect new maintainers
   * opened PR #109 for this.
* [x] update COC to include only absolute not relative links
   * COC already only contains absolute links, but fixed a url in PR #110

Perform release:

* [x] Bump version (in DESCRIPTION and NEWS) PR #113 
* [x] ~Create RC branch (for bigger releases)~ opened PR  #114 to merge dev into master
    *  asked for review from Scott (received and very helpful). Opened PRs #116 and #118 to resolve the problems found. 
* [x] `devtools::check_win_devel()` (again!)
* [x] ~`devtools::submit_cran()`~ `devtools::release()`
* [ ] ~`pkgdown::build_site()`~ (for https://docs.ropensci.org/rsnps/  it is automatically done )
* [x] Approve email

Wait for CRAN...

* [x] Tag release
* [ ] ~Merge RC back to master branch~ ( merging dev into master before submitting to CRAN)
* [x] Bump dev version
* [ ] Write blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

Template from <https://github.com/r-lib/usethis/issues/338>

**Comment by sinarueeger** [comment]
@jooolia shall we go ahead with 
1. merging this into the master first (let Scott review) and 
2. submitting to CRAN

?

**Comment by jooolia** [comment]
Hi @sinarueeger,
Yes sounds good. I guess we should also fix the version in the description to match what is in NEWS.md? I will do that right now.

**Comment by sinarueeger** [comment]
Hi Julia! Forgot about the version number... thanks for fixing that (just approved the PR).

**Comment by jooolia** [comment]
Just ran `devtools::check_win_devel()` again and now there is a new WARNING: 
https://win-builder.r-project.org/iUiM5i0dzCRa/00check.log
 checking re-building of vignette outputs ... [0s] WARNING
Error(s) in re-building vignettes:
--- re-building 'rsnps_vignette.Rmd' using knitr
Error: processing vignette 'rsnps_vignette.Rmd' failed with diagnostics:
The 'markdown' package should be declared as a dependency of the 'rsnps' package (e.g., in the  'Suggests' field of DESCRIPTION), because it contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
--- failed re-building 'rsnps_vignette.Rmd'

SUMMARY: processing the following file failed:
  'rsnps_vignette.Rmd'

So I will try following this advice and re-running to see if this solves this issue. If so I will open a PR.

**Comment by jooolia** [comment]
Hi @stefaniebutland,
@sinarueeger and I have released a new version of rsnps on CRAN. We were wondering if it might be interesting to write up a short post on this update as the package was not wholly working properly (due to a change in one of the  APIs) and we have now fixed it. 

Thanks, Julia

**Comment by stefaniebutland** [comment]
Sorry for my delay - on staycation will Sep 9 but couldn't resist coming here to say congratulations and a post sounds great.

Our [Blog Guide](https://blogguide.ropensci.org/) has most of the info you should need. In this case, it sounds like a tech note might be most appropriate, unless you wanted to include more narrative. We haven't had a post about rnsps before and you did take on co-maintenance so there are opportunities to tell a story.

Let me know when you'd like to submit a draft and I can suggest a publication date.

**Comment by jooolia** [comment]
Thanks a lot @stefaniebutland! We will mull it over and get back to you. :)

**Comment by stefaniebutland** [comment]
@jooolia @sinarueeger thoughts on tech note vs blog post and when you might want to submit a draft? (no pressure)

**Comment by jooolia** [comment]
Hi @stefaniebutland  thanks for following up. We will meet and discuss this a bit next week. Then we can let you know what we're thinking. :)

**Comment by stefaniebutland** [comment]
@jooolia have you made a decision about post or tech note? You can suggest a date for draft submission and based on that I'll propose a publication date.

**Comment by jooolia** [comment]
Thanks @stefaniebutland for following up. We will write a blog post when we will propose some new features.
