### ISSUE TITLE
New Appveyor failure on branch dev

### ISSUE THREAD

**Issue by jooolia** [ropensci/rsnps#103]
The Appveyor check on the branch "dev" has failed:

> Merge pull request #101 from ropensci/rm.obsolete.functions.sr2
> Removing obsolete functions
> 1.0.1338
> 19 minutes ago by Julia Gustavsen (committed by GitHub)
> dev 47f580e1
> Failed 18 minutes ago in 14 sec

Log available at:
https://ci.appveyor.com/project/sckott/rsnps/builds/32978641
> Build started
> $ErrorActionPreference = "Stop"
> Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
> Import-Module '..\appveyor-tool.ps1'
> The remote name could not be resolved: 'raw.githubusercontent.com'
> travis-tool.sh dump_logs
> 'travis-tool.sh' is not recognized as an internal or external command,
> operable program or batch file.
> Command exited with code 1

**Comment by sinarueeger** [comment]
@jooolia On PR #105 Appveyor actually works, but travis is failling, will investigate that.

**Comment by sinarueeger** [comment]
Reran the PR #104, and goes through now, so looks ok. Can you close this issue if it looks good to you?

**Comment by jooolia** [comment]
Thanks! I will close this. I would like to learn how to re-run these builds as it does seem like a temporary glitch.

**Comment by sinarueeger** [comment]
Hi @jooolia, I have no idea how to rerun build either. Just added a white space, so there is a change and it reruns ;-)
