### ISSUE TITLE
I want to get rs id using Chr and START END data

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [ropensci/rsnps#119]
Hello team

I have: CHR START END Effect_Allele Ref_Allele columns (hg38)

I want:  CHR START END Effect_Allele Ref_Allele RS_ID

I would like to get the SNP rs id using chromosome coordinates, please let me know how I can do this?

Thanks in advance

**Comment by sinarueeger** [comment]
Hi, 
`rsnps` maps rsids to all information, but not the other way around. 

You may want to use a biomart for that (if you have lots of data to map use a bulk download: https://m.ensembl.org/info/data/biomart/index.html or otherwise the `biomaRt` package).

HTH!
Sina

**Comment by davenomiddlenamecurtis** [comment]
One can do this with a query to ensembl's Variant Effect Predictor. Here is a link to a web page with a simple script that accepts a list of coordinates with alleles and returns rsids if they exist:

http://davecurtis.net/dcurtis/GetRsNumbers.html
