### ISSUE TITLE
How to find Disease name using RS ID number

### ISSUE THREAD

**Issue by Sububioinfo** [ropensci/rsnps#128]
Hi I have multiple  RS ID  number, Is there is any way to find the disease name using the RS ID
Here is my few RS ID, like that i have 60,000
rs17511797
rs1427263
rs3812132
rs6902288
rs614754
rs363099
rs363125
rs7118567
rs7118569
rs4808
rs348398
rs2470548
rs1531545
rs733916
rs6453022
rs2270801
rs3097773
rs11127071
rs7577677
rs17863778
rs1061093
rs9305079

**Comment by sinarueeger** [comment]
Hi, this question cannot be answered with rsnps. Please refer to other resources such as https://genetics.opentargets.org/.
