### ISSUE TITLE
Get the MAF for >1M SNPs from european reference data

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [ropensci/rsnps#150]
I have a summary stat with >1M SNPs. I would like to know if I can obtain the MAF for these SNPs from the European reference data. TIA

**Comment by jooolia** [comment]
Dear @Mahantesh-Biradar,
Sorry for the delay in the response. Does the list column `maf_population` give you the information that you need? There is a blog post here that illustrates how it can be used: https://ropensci.org/blog/2022/03/29/rsnps-update/

I will close this issue for the moment but feel free to write back with further comments. Thanks, Julia
