### ISSUE TITLE
ncbi_snp_query() is no longer able to search more than 6 SNPs at the same time

### ISSUE THREAD

**Issue by Louwai1** [ropensci/rsnps#159]
**Please do not submit bug reports for issues with the OpenSNP or NCBI’s dbSNP server itself. rsnps is only an API client, it does not have control over the server hosting the data.**

**Describe the bug**
ncbi_snp_query() is no longer able to search more than 6 SNPs at the same time. It used to be able to search hundreds of SNPs, but now breaks down when more than 6 SNPs are entered. 

**Code to reproduce**
ncbi_snp_query(c("rs10274553", "rs10509186","rs11130549", "rs12355784", "rs1354034", "rs1788103", "rs1790588", "rs1790974", "rs201979226", "rs342240"))

returns error: 
Error: lexical error: invalid char in json text.
                                       ERROR:  500 Server Error     Ca
                     (right here) ------^

**Expected behaviour**
ncbi_snp_query("rs10274553")
It still works for only a single SNP

**OS and R versions (please complete the following information):**
 - OS:  macOS Montery 12.5.1
 - R Version 4.2.2 (2022-10-31)

**Additional context**
This used to work perfectly a few days ago

**Comment by jooolia** [comment]
Dear @Louwai1,
Thank you for the bug report. I can reproduce and it seems sometimes this error occurs when 3 or 4 SNPs are included in the vector. I will look into this. 
Thanks, Julia

**Comment by jooolia** [comment]
Hi @Louwai1,
It seems that there is sporadically issues with the return of the SNPs. I have created a workaround that allows the function to be more tolerant of these status 500's. I think this is a change that I could soon push to the dev branch, but I would like to first contact the NCBI helpdesk to see if they have made any recent changes.  Thanks, Julia

**Comment by Louwai1** [comment]
Hi Julia, 

Thanks for your email! On the 12th and 13th December the function was working fine - I ran it multiple times on lists of SNPs that were over 100 SNPs long. The problem occurred since then, so hopefully that helps narrow down the window to look for changes. 

Thanks for creating such a great tool!

Best Wishes
Louwai

**Comment by jooolia** [comment]
Email sent to variation-services@ncbi.nlm.nih.gov

**Comment by jooolia** [comment]
Dear @Louwai1, the branch with the changes have been merged into the dev branch.  You can install it 

``` r
install.packages("remotes")
remotes::install_github("ropensci/rsnps")
```

I will close this issue, but I will update at a later date when I get a response from the NCBI. 

Thanks, Julia

**Comment by Louwai1** [comment]
Thanks Julia, 

I’ve tried running this line of code after installing the dev branch, but I get the following error message now:

Code:

ncbi_snp_query(c("rs2517582", "rs3130649", "rs3095353", "rs3095352", "rs539690682", "rs1264344", "rs540795529", "rs1264343", "rs3095351", "rs2535338”))

Error:

Error in if (Class %in% c("snv", "snp", "delins")) { : 
 argument is of length zero

Thanks again!

Best Wishes
Louwai

**Comment by jooolia** [comment]
Thanks @Louwai1! I will have a look in the new year. I am not near a
computer at the moment. Sorry for the delay.

Cheers, Julia

**Comment by jooolia** [comment]
Thanks @Louwai1 the error comes from rs539690682. I will work on this and let you know when a fix is available. Thanks for your help. Cheers, Julia
