### ISSUE TITLE
NCBI_snp_query returns 'position - 1'

### ISSUE THREAD

**Issue by gokceneraslan** [ropensci/rsnps#16]
Result of  `NCBI_snp_query('rs9970807')$BP` is `56499991`, however [here](http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=9970807) it is shown as `56499992`. Is this a design decision? If so, I believe it would be better to be consistent with NCBI dbSNP positions.

**Comment by sckott** [comment]
@gokceneraslan try reinstalling from Github. `devtools::install_github("ropensci/rsnps")` and trying the function again, should give correct BP location now, and reports the assembly in the output summary data.frame (#17)  - in addition, raw data is given back in addition to the summary data.frame

**Comment by gokceneraslan** [comment]
Thanks!
