### ISSUE TITLE
Specify assembly build 

### ISSUE THREAD

**Issue by sckott** [ropensci/rsnps#20]
From user: 

They want to specify a specific assembly, e.g. 37. whereas `NCBI_snp_query()` pulls from the most recent build

**Comment by bbanbury** [comment]
Thanks Scott. Following for an answer.

**Comment by kevinushey** [comment]
To the best of my knowledge, the API I query through here only allows us to access the latest build (unfortunately).

**Comment by sckott** [comment]
@bbanbury looks like we can't do it, we'll reopen this issue if we find that it can at some point

**Comment by bbanbury** [comment]
Ok, thanks for checking. Best wishes.
