### ISSUE TITLE
fetch_genotypes 

### ISSUE THREAD

**Issue by jaynal83** [ropensci/rsnps#22]
I was trying to download genotype data from opensnp using fetch_genotypes function. But when I looked at internal code, it skips 15 line by default. Actually there are some files where there is not skips at all. For example: https://opensnp.org/data/6.23andme.5

Thanks

**Comment by sckott** [comment]
@jaynal83 thanks for this!   

I wonder if things have changed, as I think all files used to require skipping 15 lines. Anyway, we'll get it fixed

**Comment by jaynal83** [comment]
Thanks for your quick response. I am currently using readLines() to read the file as plain text and then search for # character and then skip automatically, later on converting it to data frame. This is working fine so far.

**Comment by sckott** [comment]
Thanks for sharing your code

I updated `fetch_genotypes()` to be more general, reading the file whether or not there are comment lines at the top. Reinstall `devtools::install_github("ropensci/rsnps")` and try again, let me know if it works for you.

**Comment by jaynal83** [comment]
Thanks for quick update. Yes, it is working.

**Comment by sckott** [comment]
Good.
