### ISSUE TITLE
Bug in LDSearch - columnList param not working

### ISSUE THREAD

**Issue by sckott** [ropensci/rsnps#30]
this request 

http://www.broadinstitute.org/mpg/snap/ldsearch.php?snpList=rs420358&hapMapRelease=onekgpilot&hapMapPanel=CEU&RSquaredLimit=0.8&distanceLimit=500000&downloadType=file&includeQuerySnp=on&submit=search&columnList[]=DP,GA,MAF

fails, and it’s the param `columnList` that causes failure. 

It works if you only use some of the values, e.g., `columnList[]=DP`

Seems to fail when `GA` included, e.g., `columnList[]=GA`

so this query 

http://www.broadinstitute.org/mpg/snap/ldsearch.php?snpList=rs420358&hapMapRelease=onekgpilot&hapMapPanel=CEU&RSquaredLimit=0.8&distanceLimit=500000&downloadType=file&includeQuerySnp=on&submit=search&columnList[]=GA

gives 

```
SNP Proxy   Distance    RSquared    GeneVariant GeneName    GeneDescription
Error: null
```

**Comment by haozhu233** [comment]
Maybe the value of `columnList` should be DP, GP, AM?

I'm not familiar with GWAS but it seems like other people are using it in this way. 

[github.com/chengsoonong/opengwas/pull/12](https://github.com/chengsoonong/opengwas/pull/12)
[github.com/peteryin21/py-merp/blob/master/src/merp.py](https://github.com/peteryin21/py-merp/blob/master/src/merp.py)

**Comment by haozhu233** [comment]
Hmm, I see. Does that mean `GA` or `MAF` are available only for certain snps IDs? I just tried to manually do a search on that page for `rs420358` with `GA` checked and it gave me an Error. 

I guess the reason why other people use DP, GP, AM in the opengwas and python link is that these three are the default values of the output columns when you first load the page. Perhaps they are the "safest" choices you can pick?

**Comment by sckott** [comment]
Broadinstitute responded on twitter that they'll have a look https://twitter.com/broadinstitute/status/774225317145808896 

Hmmm, I have no idea, I don't really know this data.  As long as `DP, GP, AM` gives us the data we need, sounds good to me

**Comment by haozhu233** [comment]
I don't have enough knowledge for this data either.... 😫 Hope BroadInstitute can get back to us with some explanation..

Do we need to do anything with this line of code?
https://github.com/ropensci/rsnps/blob/master/R/LDSearch.R#L142

**Comment by sckott** [comment]
heard back from them 

https://twitter.com/broadinstitute/status/775388310017609728

**Comment by haozhu233** [comment]
Awesome!

**Comment by ramiromagno** [comment]
It seems this bug has been fixed upstream. So perhaps this issue should be closed?

**Comment by sckott** [comment]
this function is now defunct, the service has been taken down permanently.
