### ISSUE TITLE
`ld_search` call gives an error: `Error in stats::setNames(lapply(tmpsplit, parse_data), SNPs)`

### ISSUE THREAD

**Issue by ramiromagno** [ropensci/rsnps#35]
`ld_search("rs10510102", dataset = "onekgpilot", panel = "CEU", RSquaredLimit = 0.4, distanceLimit = 500, GeneCruiser = FALSE, quiet = FALSE)`

gives back:

`Querying SNAP...
Querying NCBI for up-to-date SNP annotation information...
Error in stats::setNames(lapply(tmpsplit, parse_data), SNPs) : 
  'names' attribute [193] must be the same length as the vector [189]
In addition: Warning message:
In if (grepl("NCBI", deparse(sys.call()))) { :
  the condition has length > 1 and only the first element will be used`

**Comment by haozhu233** [comment]
I'm closing this issue as it's duplicated with #34.
