### ISSUE TITLE
select reference build/dbsnp build in ncbi_snp_query2?

### ISSUE THREAD

**Issue by vjcitn** [ropensci/rsnps#38]
It is nice that ncbi_snp_query2 returns metadata on the reference
build used to obtain coordinates.  Can parameters be added so that
the query is issued to select earlier builds?  I didn't find anything
obvious in the NCBI eutils documentation, but

https://www.ncbi.nlm.nih.gov/variation/view/?q=rs6060535&filters=source:dbsnp&assm=GCF_000001405.33   # is GRCh38

while

https://www.ncbi.nlm.nih.gov/variation/view/?q=rs6060535&filters=source:dbsnp&assm=GCF_000001405.25  # is GRCh37

Thanks

**Comment by sckott** [comment]
will take a look

**Comment by sckott** [comment]
looked around a bit, didn't see anything yet, will ask some folks

**Comment by vjcitn** [comment]
much appreciated.  if it is not supported it at NCBI it should be and i
would be happy
to help lobby them if necessary.

On Thu, Jan 19, 2017 at 8:00 PM, Scott Chamberlain <notifications@github.com

**Comment by dwinter** [comment]
Hi both, 

I've run into this a few times with `rentrez` users, and came to the conlusion the older locations are just not available via EUtils ([there are a few Biostars threads about this too](https://www.biostars.org/p/131413/)). i have checked all of the output formats, and they all produce information only on the latest build. 

EUtils also doesn't have a liftover-like tool for converting locations (though ensembl does, I started something to make use of it a while back: https://github.com/dwinter/rensembl/blob/master/R/mapping.r), so I'm not sure there is much `rsnp` can do at present 😞 .

**Comment by vjcitn** [comment]
Bioconductor rtracklayer package has a liftOver method, and AnnotationHub
provides the chain
files.  So R users can do the conversion if the older annotations are
unavailable.

If you would like, I could create a pull request that adds a function and
documentation to illustrate
this process.  You could add the Bioconductor packages to the Suggests
field of DESCRIPTION.
Otherwise I will add the software to one of my packages, and "Suggest"
rsnps -- as long as you
intend to keep rsnps on CRAN.

Off-topic: have rsnps added to the "Genetics" task view at CRAN?

**Comment by sckott** [comment]
> If you would like, I could create a pull request that 

please do

> Off-topic: have rsnps added to the "Genetics" task view at CRAN?

yeah, i can ask
