### ISSUE TITLE
Could you please make it optinal to call `ncbi_snp_query2` in `ld_search`?

### ISSUE THREAD

**Issue by erikyao** [ropensci/rsnps#41]
Hi Scott, Kevin & Hao,

I am using SNAP to collect negative examples for my regulatory SNP classification research and I really appreciate your work! It saves me a lot of time!

However, I don't understand why you would call `ncbi_snp_query2` inside `ld_search`, because in my situation I hardly use the NCBI columns from the results. Is it possible for you to make this calling an option? Sorry if I missunderstood your design.

Best regards,
Yao

**Comment by sckott** [comment]
thanks for your question @erikyao - will have a look

**Comment by sckott** [comment]
@erikyao why is it a problem to add the additional NCBI columns?  Is it that you think it takes too long?

**Comment by sckott** [comment]
if we add a toggle for adding ncbi data or not, and benchmark  it:

```r
microbenchmark::microbenchmark(
  add_ncbi = ld_search("rs420358", add_ncbi = TRUE),
  dont_add_ncbi = ld_search("rs420358", add_ncbi = FALSE) ,
  times = 5
)
#> Unit: seconds
#>                   expr           min              lq         mean     median            uq           max neval
#>           add_ncbi 3.464241 3.602968 3.649860 3.669314 3.674416 3.838362     5
#>   dont_add_ncbi 2.765132 2.783538 2.874335 2.866442 2.916187 3.040377      5
```

so it's a bit faster to not add the ncbi data, but not much. 

you can easily drop those columns after you use the fxn as an alternative

**Comment by sckott** [comment]
@erikyao i'll close this soon if we don't hear back from you soon - so let me know soon

**Comment by erikyao** [comment]
Sorry for replying late. Yes, just a concern of the speed. Thank you anyway!

**Comment by sckott** [comment]
@erikyao is the speed difference important to you?  or not that big of a deal?

**Comment by erikyao** [comment]
Actually not a big deal. Just a suggestion.

**Comment by sckott** [comment]
okay, thanks, since it's not a huge speed improvement, i'll close this for now, we can revisit it in the future if others want a similar change
