### ISSUE TITLE
Plot function for output of ld_search?

### ISSUE THREAD

**Issue by zx8754** [ropensci/rsnps#47]
It would be nice if `ld_search` returned a result with "method", so default plot function could be used to plot *Position* as xaxis vs *RSquared* value as yaxis.

Example:
```R
x <- ld_search("rs420358")

# instead of this:
plot(x$rs420358$bp_NCBI, x$rs420358$RSquared, xlab = "Position", ylab = bquote("R"^2))

# we could maybe simply:
plot(x, snp = "rs420358")

# or "plot = TRUE" option?
x <- ld_search("rs420358", plot = TRUE)
```

**Comment by sckott** [comment]
thanks @zx8754 

nice idea. I think we can do this, but i'd prefer a different option:

```r
x <- ld_search("rs420358")
plot(x)
```

thoughts? that way we don't alter the fxn as is, but we support plotting with a S3 plot method that we include in the package so `plot` dispatches correctly with the output of `ld_search`

**Comment by zx8754** [comment]
I added `snp = ` arg to the plot as `ld_search` returns a lists of dataframes per each query SNP, so we could tell which one of them to plot.

**Comment by sckott** [comment]
yeah, we could do that with the approach I suggested as well though - which i think is better since the download step only has to be done once and then user can select which snp to plot

**Comment by sckott** [comment]
this function is now defunct, the service has been taken down permanently.
