### ISSUE TITLE
Use beagle data for ld_search?

### ISSUE THREAD

**Issue by zx8754** [ropensci/rsnps#48]
This package uses beagle RSquared data to get proxies:
https://github.com/slowkow/proxysnps

beagle RSquared data folder, which includes 1KG Phase 3 data:
http://bochet.gcc.biostat.washington.edu/beagle/1000_Genomes_phase3_v5a/

Could this be an option for `ld_search`?
```R
ld_search(SNPs, dataset = "beagle") 
```

**Comment by sckott** [comment]
@zx8754 thanks for the issue. 

maybe, i assume you mean import that pkg and use it here?

**Comment by zx8754** [comment]
I would prefer not to have too many dependencies, maybe steal/merge the code/packages :) ?

Beagle has the latest 1KG panel, that's why I thought maybe use it as source to get "latest" ld.

**Comment by sckott** [comment]
where exactly in that pkg does it get beagle data?

**Comment by zx8754** [comment]
It is getting it from this folder:
http://bochet.gcc.biostat.washington.edu/beagle/1000_Genomes_phase3_v5a/individual_chromosomes/

Using tabix through RCurl, see:
https://github.com/slowkow/proxysnps/blob/master/R/get_vcf.R#L106

Also, just noticed that *proxysnps* depends on bioconductor package - `myvariant::queryVariant(query)`: https://github.com/slowkow/proxysnps/blob/master/R/get_proxies.R#L53

**Comment by sckott** [comment]
thanks for that.

**Comment by sckott** [comment]
@zx8754 sorry about delay here, just been very busy. 

`beagle` isn't an option in the http://archive.broadinstitute.org/mpg/snap/ldsearch.php service `ld_search` uses. So I don't think it makes sense to include in this function. 

We could consider a new function to get this beagle data, thoughts?  Would i make sense to add here if its a separate function, or did you think only made sense if it was part of `ld_search`?

**Comment by sckott** [comment]
this function is now defunct, the service has been taken down permanently.
