### ISSUE TITLE
Error in ncbi_snp_query2(proxy_SNPs) : Request-URI Too Long (HTTP 414).

### ISSUE THREAD

**Issue by janhuangcn** [ropensci/rsnps#51]
I ran the below script in R. It returned error as below.

I think it is because I set a very low RSquaredLimit. Because I want to check all LD information. Is there a way to solve this problem? 

    SNAP<- ld_search("rs116785524", GeneCruiser = FALSE, dataset = "onekgpilot", panel = "CEU", RSquaredLimit = 0.1, distanceLimit = 500)
    Querying SNAP...
    Querying NCBI for up-to-date SNP annotation information...
    Error in stats::setNames(lapply(tmpsplit, parse_data), SNPs) :  'names' attribute [227] must be the same length as the vector [223]
    In addition: Warning message:
    In if (grepl("NCBI", deparse(sys.call()))) { : the condition has length > 1 and only the first element will be used

**Comment by sckott** [comment]
thanks for your question. please paste in your `sessionInfo()`

**Comment by sckott** [comment]
i think this is the same issue as #50 , but we'll leave open for now

**Comment by janhuangcn** [comment]
Thank you. It is solved by installing from github devtools::install_github("ropensci/rsnps")
