### ISSUE TITLE
ld_search failing: Broad Institute service down

### ISSUE THREAD

**Issue by sckott** [ropensci/rsnps#53]
Anyone know if it's just a short blip in service or if it's down for good?

An example URL sent when calling `ld_search`  

http://archive.broadinstitute.org/mpg/snap/ldsearch.php?snpList=rs113196607&hapMapRelease=onekgpilot&hapMapPanel=CEU&RSquaredLimit=0.8&distanceLimit=500000&downloadType=file&includeQuerySnp=on&submit=search&columnList%5B%5D=DP%2CGA%2CMAF

but then error message is 

Server returned HTTP response code: 502 for URL: http://genecruiser.broadinstitute.org/genecruiser3_services/rest/variation/byName?email=gap@broad.mit.edu&name=rs13052546+rs13051259+rs9976134+rs13052090+rs2836551+rs9977611+rs2212596+rs2244890&firstResult=0

**Comment by letaylor** [comment]
Perhaps this is the issue?

http://software.broadinstitute.org/cancer/software/genepattern/blog/2016/03/15/genecruiser-is-now-deprecated

**Comment by sckott** [comment]
@letaylor  ah thanks very much, that probably is the reason
