### ISSUE TITLE
Issue: Curl couldn't connect ncbi_snp_query

### ISSUE THREAD

**Issue by sariya** [ropensci/rsnps#54]
<details> <summary><strong>Session Info</strong></summary>

```r
sessionInfo() 
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /mnt/mfs/cluster/bin/R-3.4/lib/libRblas.so
LAPACK: /mnt/mfs/cluster/bin/R-3.4/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rsnps_0.2.0

loaded via a namespace (and not attached):
 [1] httr_1.3.1     compiler_3.4.2 magrittr_1.5   plyr_1.8.4     R6_2.2.2      
 [6] tools_3.4.2    curl_3.1       Rcpp_0.12.15   stringi_1.1.6  stringr_1.3.0 
[11] XML_3.98-1.10 
```
</details>

Hello, 

I'd like to use rsnps to get chromosome position of the SNP however my command fails as:

`ncbi_snp_query("rs62635278")`
`Error in curl::curl_fetch_memory(url, handle = handle) : `
  `Couldn't connect to server`

I export proxy settings for my cluster but that doesn't help.

`export http_proxy=http:/.....`

Tried with https: 
`export https_proxy=http:/.....`

I installed rsnps on local using 

`R CMD INSTALL rsnp.gz -l ~/R_LIB`

Any suggestions?

**Comment by sckott** [comment]
sorry for the delay @sariya 😢 

that code works for me right now, i wonder if the service was just down temporarily - can you try again?

**Comment by sariya** [comment]
Thanks. 
Sorry for the delay in writing back. It works on my end. :)

**Comment by sckott** [comment]
glad it works
