### ISSUE TITLE
Missing information?

### ISSUE THREAD

**Issue by privefl** [ropensci/rsnps#62]
```r
ID <- c("rs4301695", "rs17495050", "rs5024522", "rs9422868", "rs9422871")
rsnps::ncbi_snp_summary(ID)
```
is returning 4 rows only.

This was tested with the latest CRAN and GitHub versions.

**Comment by sckott** [comment]
thanks for the report

Seems like it's not there

```r
ncbi_snp_summary("rs5024522")
#> data frame with 0 columns and 0 rows
```

The URL request:

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=snp&retmode=flt&rettype=flt&id=5024522&api_key=<your key>

gives `UID=5024522: cannot get document summary`

1. should data be found for that ID?
2. when ids are not found, would you prefer a row for that id with NA's for all fields?

**Comment by privefl** [comment]
Yes, I would have expected to have NA's.

**Comment by sckott** [comment]
@privefl can you reinstall, reload R, and try again, should be fixed. 

new first column that's the queried SNP, as it can sometimes be different from the SNP id returned by Entrez

**Comment by privefl** [comment]
Thanks.
But, why put NA's at the end and not returning results in the same order that they were queried?

**Comment by sckott** [comment]
the order they are given to ENTREZ is not maintained in the response they give. but I can reorder it

**Comment by privefl** [comment]
That would be awesome 👍

**Comment by sckott** [comment]
try again now

**Comment by privefl** [comment]
Seems to work. Thanks.

Would you be interested in some parallel / blockwise implementation for large queries?
