### ISSUE TITLE
Reorder output dataframes so that chromosome and bp are beside each other

### ISSUE THREAD

**Issue by jooolia** [ropensci/rsnps#70]
It could be helpful to have chromosome and bp next to each other in the output dataframes.
e.g

``` r
ncbi_snp_query("rs420358")
#>      Query Chromosome   Marker Class Gene Alleles Major Minor MAF       BP AncestralAllele
#> 1 rs420358          1 rs420358   snp <NA>   A,G,T     A     G  NA 40341239     T,T,T,T,T,T
```

Would become:
``` r
#>      Query Chromosome  BP      Marker     Class Gene Alleles Major Minor MAF      AncestralAllele
#> 1 rs420358          1 40341239 rs420358   snp <NA>   A,G,T     A     G  NA      T,T,T,T,T,T
```

**Comment by jooolia** [comment]
Hi @sinarueeger , I know that some of these issues will be closed when we merge dev into master, but would it be possible to either close them when we have done the work (even if in dev) or to add a label "fixed_in_dev" or something like that? For me it would be helpful to know which issues still need to be tackled when looking at the list of issues. 
Julia

**Comment by sinarueeger** [comment]
Hi @jooolia, of course. Let's close issues as we fix them. I let you pick an approach

**Comment by jooolia** [comment]
Closing issue as fixed (and function deprecated).
