### ISSUE TITLE
New version > CRAN

### ISSUE THREAD

**Issue by sinarueeger** [ropensci/rsnps#71]
The CRAN version is outdated (0.3.0) and should be updated with either this current version (0.3.1.9113) or after updating a few other things. 

@jooolia what do you prefer: upload to CRAN immediately or shall we first add a few more enhancements?

We'd need to add for sure another section in [NEWS](https://github.com/ropensci/rsnps/blob/master/NEWS.md).

**Comment by jooolia** [comment]
Hi @sinarueeger,
Shall we see if we can add a few enhancements and then prepare a new release and CRAN submission? What time frame would best work with this nice momentum you've created with all these nice issues? One idea would be to give ourselves until June to add/update and then we could prepare a new version. What do you think?

**Comment by sinarueeger** [comment]
@jooolia 
End of May/beginning of June sounds reasonable to me! This gives us enough time too with following the guidelines. 
Here is the waiting line for CRAN: https://cransays.itsalocke.com/articles/dashboard.html

**Comment by jooolia** [comment]
From https://github.com/r-lib/usethis/issues/338

Prepare for release:

* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [ ] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`

Perform release:

* [ ] Create RC branch (for bigger releases)
* [ ] Bump version (in DESCRIPTION and NEWS)
* [ ] `devtools::check_win_devel()` (again!)
* [ ] `devtools::submit_cran()`
* [ ] `pkgdown::build_site()`
* [ ] Approve email

Wait for CRAN...

* [ ] Tag release
* [ ] Merge RC back to master branch
* [ ] Bump dev version
* [ ] Write blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

Template from <https://github.com/r-lib/usethis/issues/338>

**Comment by jooolia** [comment]
`devtools::check_win_devel()`
message received at j.gustavsen@gmail.com
winbuilder: Package rsnps_0.3.2.9121.tar.gz has been checked and built
Dear package maintainer,

this notification has been generated automatically.
Your package rsnps_0.3.2.9121.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/YG7J3d15Hs0W
The files will be removed after roughly 72 hours.
Installation time in seconds: 12
Check time in seconds: 118
Status: 1 NOTE
R Under development (unstable) (2019-05-23 r76587)

All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)

**Comment by jooolia** [comment]
`rhub::check_for_cran()`
Success!

From  R-hub builder <support@rhub.io>

>Build ID: | rsnps_0.3.2.9121.tar.gz-1eeac7dd6ef64d32a17e50d73ef866ec
>Platform: | Windows Server 2008 R2 SP1, R-devel, 32/64 bit
> NOTES:
>* checking CRAN incoming feasibility ... NOTE
>  Version contains large components (0.3.2.9121) 
>Maintainer: 'Julia Gustavsen <j.gustavsen@gmail.com>'  
>New maintainer: 
>Old maintainer(s):   Scott Chamberlain <myrmecocystus@gmail.com> 
 > Julia Gustavsen <j.gustavsen@gmail.com>
>See the full build log: [HTML](https://builder.r-hub.io/status/rsnps_0.3.2.9121.tar.gz-1eeac7dd6ef64d32a17e50d73ef866ec)

Same NOTE with: 
Build ID: | rsnps_0.3.2.9121.tar.gz-3d444ec77f0e42cb9e77b598658bbf10
Platform: | Ubuntu Linux 16.04 LTS, R-release, GCC
and 
Build ID: | rsnps_0.3.2.9121.tar.gz-14b94f50315b46d28e01557e79810771
Platform: | Fedora Linux, R-devel, clang, gfortran

**Comment by jooolia** [comment]
I got an error running `revdepcheck::revdep_check(num_workers = 4)`

I runs through section "INIT", and "INSTALL - Installing CRAN version of rsnps" and then fails on "Installing DEV version of rsnps" with message: 
Error in is.na(remote_deps$package) : 
  (converted from warning) is.na() applied to non-(list or vector) of type 'NULL'
Running `revdepcheck::revdep_details(revdep = "rsnps")`
gives: "Error in db_results(pkg, revdep)[[1]] : subscript out of bounds" 

There is a github issue https://github.com/r-lib/revdepcheck/issues/213 that describes a similar issue, but I am not sure it is not something on my end. I will try later on my windows partition and report back. @sinarueeger, maybe you could also try if you get a spare moment? Thanks, Julia

**Comment by sinarueeger** [comment]
Hi @jooolia, I ran the following: 
```
revdepcheck::revdep_reset()
revdepcheck::revdep_check(num_workers = 4)
```

This is the console output it produced: 
![image](https://user-images.githubusercontent.com/4454726/58386342-acdb8880-7ffe-11e9-853b-77e8d71ef828.png)

I got some failures reported: 
- [`revdep/failures.md`](https://github.com/ropensci/rsnps/blob/T71-revdep/revdep/failures.md)

I will dig into this the following few days. 
And let me know if I can help with your issue.

**Comment by jooolia** [comment]
Hi @sinarueeger,
Thanks for checking. I successfully ran it on my windows partition. I get the same failures as you, in appreci8R. I think it is because it is a Bioconductor package. 
I think what we need to tell revdep to check Bioconductor also, so we should run: 

`revdepcheck::revdep_reset()
revdepcheck::revdep_check(num_workers = 4, bioconductor = TRUE)`

I will try this tonight. :)

**Comment by sinarueeger** [comment]
Hey @jooolia,
I just checked: 
- By default my revdep version runs `revdepcheck::revdep_check(num_workers = 4, bioc = TRUE)`. So at least in my case, bioconductor was already checked. 
- `appreci8R` is on bioconductor since [0.5 years](https://bioconductor.org/packages/release/bioc/html/appreci8R.html). The last revdep check on the master ran 8 months ago. Hence `appreci8R` was not a problem in the last revdep run. 
- I don't know why it won't work. The problem might be the installation of these databases like `BSgenome.Hsapiens.UCSC.hg19`.

A quick googling showed that stringr also failed revdep for [`appreci8R`](https://github.com/tidyverse/stringr/blob/master/revdep/README.md).

We could ask others on ropensci slack how they deal with revdep failures. What do you think?

**Comment by jooolia** [comment]
Hi @sinarueeger,
Thanks for the comments. Yes you were right that Bioconductor is checked by default. :) Thanks to your comment about the installation of the genome databases I tested allowing a longer time for running the check and it passed!

`library(revdepcheck)
revdep_reset()
revdep_check(num_workers = 4, timeout = as.difftime(360,units = "mins"))
`

Checking the time stamps I don't think we needed 360 minutes, but it took over 60 mins to successfully run the check. 

Which gives no failures and no problems and all checks are ok.

**Comment by jooolia** [comment]
I now see that the revdep folder is in the repo. I will create a pull request to add the updated folder to the repo.

**Comment by jooolia** [comment]
Hi @sinarueeger,
I don't remember what we decided on, but do we want to "Create RC branch (for bigger releases)" or do we stick with our dev branch for now? Shall we ask Scott to have a look now or should we run `devtools::check_win_devel()` again? I would vote for sticking with the dev and asking for a look now (and then `running check_win_devel()` right before we `release()`), but these are weakly held opinions so let me know your thoughts. :)

**Comment by sinarueeger** [comment]
Hi @jooolia, 
Since these are small changes to be pushed to the master, I also think we can stick to the `dev` branch. 
I also vote for asking Scott now, then running `devtools::check_win_devel()`.

**Comment by sckott** [comment]
- found something weird, when I run document/install, it removes the two man files for NCBI_snp_query.Rd and NCBI_snp_query2.Rd - which I think is correct because the deprecated-defunct.R file has the rdnames as with "-defunct" on the end of the name - but then when i run check it reports that it can't find ncbi_snp_query and ncbi_snp_query objects in manual references. Anyway, if I delete all man files and rerun docuemnt/install then check again, all is good
- all looks good in your checklist, one other thing: make sure to update the codemeta.json before submitting
- the links at the bottom of the COC file need fixing - noticed this in all my pkgs and have been fixing as I go, both should be `https://...etc`
- looks like you have 2 of the same heading in your news file https://github.com/ropensci/rsnps/blob/dev/NEWS.md#rsnps-032 and then a heading with no news in it https://github.com/ropensci/rsnps/blob/dev/NEWS.md#rsnps-031
- should update the LICENSE file to have copyright holder be one or both of you

**Comment by sckott** [comment]
one more thing: CRAN are now checking that you don't have relative links in docs - so e.g. need to give full link to the Code of conduct file instead of the relative link, and so on - usually this happens with links to COC file and if you link to a CONTRIBUTING.md file

**Comment by jooolia** [comment]
Hi @sckott! Thanks a lot for your comments! Very helpful. We also were scratching our heads a bit with the weird behaviour of the .Rd files. 
We will fix these other issues, run our checks and then submit. 
Julia

**Comment by sinarueeger** [comment]
Thanks, @sckott! 

Regarding the header with no news in it: https://github.com/ropensci/rsnps/blob/dev/NEWS.md#rsnps-031. 

Is it ok to jump from 0.3.0 to 0.3.2? 

And I could not find any more relative links in the docs (other than the COC file).

**Comment by jooolia** [comment]
This has been superseeded by #102 where we will prepare for a new CRAN release.
