### ISSUE TITLE
All NCBI functions failing

### ISSUE THREAD

**Issue by sinarueeger** [ropensci/rsnps#86]
Since 2019-07-01 (or before) #85, all NCBI functions are failing. 

```
library(rsnps)
x <- c("rs420358", "rs1837253", "rs1209415715")
aa <- ncbi_snp_query(x)
```

I added my NCBI authentication, just to check if the API key is the missing bit. 

There might have been a change at NCBI: 
https://www.ncbi.nlm.nih.gov/books/NBK25500/

**Comment by sinarueeger** [comment]
This could be the reason: 
https://www.ncbi.nlm.nih.gov/projects/SNP/SNPeutils.htm
![image](https://user-images.githubusercontent.com/4454726/60586220-eb006080-9d91-11e9-960e-81736354236e.png)

**Comment by jooolia** [comment]
Thanks for looking into this @sinarueeger. I have not looked into the format differences (but will try to tonight). Do you have a feeling whether we could quickly change the functions to use this new format or something that would take some time and thought?

**Comment by sinarueeger** [comment]
I have not explored everything yet, but I would say that a format change just means to rewrite parts of the code. The annoying bit is, that some headers have changed too. E.g. before there were `rsID`'s, now it is `uid`. So we will need to take a few decisions on that front.

**Comment by sinarueeger** [comment]
Hi @jooolia, 
I have hacked myself through the `ncbi_snp_query()` function in a way that it works now. 
Here is the link to the branch: https://github.com/ropensci/rsnps/tree/new.ncbi.format

It is **really** not pretty. If we decide that this works, I would suggest that we do it from scratch. 

The other not working function is `ncbi_snp_query2()`. I think this is gonna be a bit more complicated. Although the resulting matrix is quite similar, the underlying code of these two functions is quite different. 

I am actually thinking if we could just add the features that `ncbi_snp_query2()` to the data.frame that `ncbi_snp_query()` outputs and create a wrapper. That way we would avoid this redundancy of code and we could slowly retire `ncbi_snp_query2()`. For example: 

```
ncbi_snp_query <- function(SNPs, ...)
{
   ## do stuff
   ## extract "Query", "Chromosome", "BP", "Marker", "Class", "Gene", "Alleles",
    "Major", "Minor", "MAF", "AncestralAllele"
   ## extract organism, assembly
}

ncbi_snp_query2 <- function(SNPs, ...)
{
   out <- ncbi_snp_query(SNPs, ...)
   out %>%  rename so that all lower case + add organism + assembly

  
}
```

**Comment by jooolia** [comment]
These functions have been replaced by ncbi_snp_query_api() and thus this will be closed.
